language: java
jdk:
  - openjdk8

before_install:
  - openssl aes-256-cbc -K $encrypted_585c2d4ca350_key -iv $encrypted_585c2d4ca350_iv -in private.der.enc -out private.der -d

after_success:
  - ./gradlew jacocoTestReport coveralls

env:
  global:
    # COVERALLS_REPO_TOKEN
    secure: VxKH0LZljHph5dOqrsQVzfz5adLGgORDfKvTJHO4CWNviK0FhZYyDgnsBO0HOoOf8qxkfZj/VOR3bcbfyjtWGOhfd+Lv2ezcNUvArRBqf+nFs5xEF8x6m35SKWUF1o88LXI/TQm2jryB7uO1092ZdZgLcEgzGaua8qrZFzSm1mY+8jAF40yEMiEnQ225is+OrtvZOBwSox/Ls/YFEQsR+273+haDFRr+lWFNEFPLgSPV4v1YDkVw4x1mg4UydVIKN7Ya9+v0+msyA546MNzsXOgHyEU9siHX7qs6SuRcTG9X2A1FbAMo2KcUW/20d8IZxEZJc45MnfzJe3EtwVcwn9eqwzivUwAuUrbfUq63A+RgX6tOkjkhEt5W6M7Es3R13gdwRInAeBlF0DKgruzhOOZ787r7SpMEeGgmkKj8T7eoBlcFMMduKEUzF3GKBgLX4/qAxFmQixkNWx1e0MyRuZe1pzzExDQpxnwK9IebcZ8gmuYGZB8AWGkCSdGoyMa78tGKgvVBaGO55a2+r94SS2re5m7NJDIZFDKuumQHqt2KQEkbJJi/N0xO2F2m5Qt89Ia9bx4+DWevWOKDGNiR1Evd3XJEo7WH2BnNnyTNJF4EwMEogH0KoAb+UMpl/+ytQkaB7RzRKXaly+N3UmYmu9oWUNpYTK0ZtjNlQThwe/Q=
