swagger: '2.0'
info:
  title: Brassring
  description: Documentation of API,models for Brassring
  version: v1

definitions:
  BrassRingV1Action:
    type: string
    description: Possible actions for BrassRing V1 connector.
    enum:
      - Update

  Status:
    type: object
    properties:
      Code:
        type: integer
      ShortDescription:
        type: string
      LongDescription:
        type: string

  CANDIDATE:
    type: object
    properties:
      CANDIDATEID:
        description: "This is the unique identifier of the Candidate in the BrassRing system"
        type: integer
        format: int64
      REQUISITIONNUMBER:
        description: "This is the Client Req number also referred as the Optional Req Number. The value will be blank if client does not use it."
        type: string
      BRREQNUMBER:
        description: "This is the unique identifier of the Job in BrassRing. It is always a value that ends with “BR”, for example 100 BR, 3423BR, etc."
        type: string
      JOBCODE:
        description: "This is the standard job code associated with the Job"
        type: string
      STATUS:
        description: "This is the HR Status value that triggered the candidate/new hire integration"
        type: string
      CANDIDATEFIRSTNAME:
        description: "Candidate first name"
        type: string
      CANDIDATELASTNAME:
        description: "Candidate last name"
        type: string
      DATEOFBIRTH:
         description: "Candidate date of birth"
        type: string
      BIRTHPLACE:
         description: "Candidate birth place"
        type: string
      COUNTRYOFBIRTH:
        description: "Candidate country birth place"
        type: string
      GENDER:
        description: "Candidate gender"
        type: string
      MARITALSTATUS:
        description: "Candidate martial status"
        type: string
      NATIONALITY:
        description: "Candidate nationality"
        type: string
      LANGUAGENAME:
        description: "Candidate native language"
        type: string
    required:
      - CANDIDATEID
      - BRREQNUMBER
      - STATUS
